---
- name: Show Commands
  hosts: blacklan
  gather_facts: false
  connection: network_cli


  tasks: 
    - name: Conf t
      ios_config:
        lines:
          - ip domain-name blacklan.local
          - ntp server 194.146.251.100
          - clock  timezone UTC 2
        save_when: always
