blacklan:
  children:
    routers:
      hosts:
        cisrt1001.blacklan.local:
        cisrt1002.blacklan.local:
        cisrt1003.blacklan.local:
    switches:
      hosts: 
        cissw1002.blacklan.local:
        cissw1003.blacklan.local:
        gojsw1001.blacklan.local:
  vars:
    ansible_network_os: ios
    ansible_user: mszczechla
    ansible_password: Makofinal10
    ansible_connection: network_cli
    ansible_host_key_checking: false

