---
- name: Show Commands
  hosts: routers
  gather_facts: false
  connection: network_cli


  tasks: 
    - name: MD5 
      ios_command:
        commands:
        - "verify /md5 flash:isr4300-universalk9.16.09.06.SPA.bin"
        wait_for:
        - result[0] contains "08d876e4eca745843e8aa69a9cf1cb3e"
        retries: 1
      register: md5_result
      vars:
        ansible_command_timeout: 100
    - debug:
        msg:
        - "md5 is: {{ md5_result }}" 